In [ ]:
Задание 1
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
- оценка 2 и меньше - низкий рейтинг
- оценка 4 и меньше - средний рейтинг
- оценка 4.5 и 5 - высокий рейтинг
Результат классификации запишите в столбец class

In [6]:
import pandas as pd

def classificate_movies(rate):
    if rate <= 2:
        return 'низкий рейтинг'
    elif rate <= 4:
        return 'средний рейтинг'
    elif rate >= 4.5:
        return 'высокий рейтинг'
    else:
        return 'нет оценки'

movies = pd.read_csv('ratings.csv')
movies['class'] = movies['rating'].apply(classificate_movies)

movies.head()

   userId  movieId  rating   timestamp            class
0       1        2     3.5  1112486027  средний рейтинг
1       1       29     3.5  1112484676  средний рейтинг
2       1       32     3.5  1112484819  средний рейтинг
3       1       47     3.5  1112484727  средний рейтинг
4       1       50     3.5  1112484580  средний рейтинг

In [ ]:
Задание 2 Используем файл keywords.csv. Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’. Правила распределения по регионам Центр, Северо-Запад и Дальний Восток: geo_data = { 'Центр': ['москва', 'тула', 'ярославль'],
'Северо-Запад': ['петербург', 'псков', 'мурманск'],
'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск'] } Результат классификации запишите в отдельный столбец region.

In [4]:
import pandas as pd

geo_data = {

    'Центр': ['москва', 'тула', 'ярославль'],

    'Северо-Запад': ['петербург', 'псков', 'мурманск'],

    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']

}

keywords_df = pd.read_csv('keywords.csv')

def region_func(row):

    index_geo = 'undefined'
    linelist = row['keyword'].split(' ')  
    
    for line in linelist:
        for key, value in geo_data.items():
            if line in value : 
                index_geo = key
                return index_geo
                
    return index_geo

keywords_df['region'] = keywords_df.apply(region_func, axis=1)

filtered_keywords = keywords_df[ (keywords_df['region']=='Центр') | (keywords_df['region']=='Северо-Запад') | (keywords_df['region']=='Дальний Восток') ]
filtered_keywords.head()

                       keyword   shows          region
127               авито москва  979292           Центр
370   авито ру санкт петербург  425134    Северо-Запад
849            авито ярославль  209581           Центр
1063       фарпост владивосток  176951  Дальний Восток
1236      банк санкт петербург  174375    Северо-Запад